### ISSUE TITLE
No sweep_dump  in the device for RSSI

### ISSUE THREAD

**Issue by avashist003** [seemoo-lab/nexmon-arc#3]
After following the steps to access the RSSI and SNR using the nexmon-arc as mentioned, and then copying the patched wil6210.fw in the device sweep_dump is not found in the location:

/sys/kernel/debug/ieee80211/phy2/wil6210/sweep_dump

**Comment by dsteinmetzer** [comment]
This file is part of the our extended wil6210 device driver. Please check our extensions here:
 https://github.com/seemoo-lab/lede-ad7200/tree/release/overlay/seemoo/mac80211/patches
